								18 July 93
COPY172 is a modification of the COPY routine provided for ZSDOS support and
updated by Howard Goldstein as COPY171.  This version adds the ability to
handle NZTIME stamps in addition to P2DOS (CP/M+), DosDisk(tm) and DateStamper
(tm) stamps.  The code to scan the library with File Stamps is now included in
the source code over a DSLIB routine.			H.F.Bower
